// dailyQuotes.js - 120+ Curated daily inspirational quotes for students
// Focus: Study & learning motivation, character, kindness, perseverance, curiosity, and growth.

export const DAILY_QUOTES = [
    { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
    { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { quote: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
    { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { quote: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "Character is doing the right thing when nobody's looking.", author: "J.C. Watts" },
    { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { quote: "In a world where you can be anything, be kind.", author: "Clare Pooley" },
    { quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { quote: "You do not have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "We rise by lifting others.", author: "Robert Ingersoll" },
    { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { quote: "Integrity is choosing courage over comfort and what is right over what is easy.", author: "Brené Brown" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { quote: "Curiosity is the wick in the candle of learning.", author: "William Arthur Ward" },
    { quote: "Treat everyone with politeness and kindness, not because they are nice, but because you are.", author: "Roy T. Bennett" },
    { quote: "Mistakes are proof that you are trying.", author: "Unknown" },
    { quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
    { quote: "Wherever there is a human being, there is an opportunity for a kindness.", author: "Lucius Annaeus Seneca" },
    { quote: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher" },
    { quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
    { quote: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
    { quote: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
    { quote: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr." },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "Be curious, not judgmental.", author: "Walt Whitman" },
    { quote: "To know what is right and not do it is the worst cowardice.", author: "Confucius" },
    { quote: "A warm smile is the universal language of kindness.", author: "William Arthur Ward" },
    { quote: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
    { quote: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", author: "John Quincy Adams" },
    { quote: "You don't need a reason to help people.", author: "Unknown" },
    { quote: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
    { quote: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
    { quote: "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not.", author: "Oprah Winfrey" },
    { quote: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "Generosity is giving more than you can, and pride is taking less than you need.", author: "Kahlil Gibran" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "Small acts, when multiplied by millions of people, can transform the world.", author: "Howard Zinn" },
    { quote: "Strive for progress, not perfection.", author: "Unknown" },
    { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
    { quote: "Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.", author: "Alfred Adler" },
    { quote: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "Always be a little kinder than necessary.", author: "J.M. Barrie" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { quote: "Character, not circumstances, makes the person.", author: "Booker T. Washington" },
    { quote: "Knowledge will bring you the opportunity to make a difference.", author: "Claire Fagin" },
    { quote: "Be somebody who makes everybody feel like a somebody.", author: "Brad Montague" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Do good by stealth, and blush to find it fame.", author: "Alexander Pope" },
    { quote: "Perseverance is failing 19 times and succeeding the 20th.", author: "Julie Andrews" },
    { quote: "Education is not the learning of facts, but the training of the mind to think.", author: "Albert Einstein" },
    { quote: "The best way to cheer yourself up is to try to cheer somebody else up.", author: "Mark Twain" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Every day is a chance to begin again, to learn something new, and to do better.", author: "Unknown" },
    { quote: "Humility is not thinking less of yourself, it's thinking of yourself less.", author: "C.S. Lewis" },
    { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { quote: "Kindness begins with the understanding that we all struggle.", author: "Charles Glassman" },
    { quote: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" },
    { quote: "Today is an opportunity to get better. Don't waste it.", author: "Unknown" },
    { quote: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
    { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "There is no exercise better for the heart than reaching down and lifting people up.", author: "John Holmes" },
    { quote: "You are always a student, never a master. You have to keep moving forward.", author: "Conrad Hall" },
    { quote: "Gentleness and kindness will make our homes a paradise on earth.", author: "C.A. Bartol" },
    { quote: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { quote: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author: "Lao Tzu" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Character is like a tree and reputation like a shadow. The tree is the real thing.", author: "Abraham Lincoln" },
    { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { quote: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
    { quote: "Success doesn't come to you, you go to it.", author: "Marva Collins" },
    { quote: "Good character is not formed in a week or a month. It is created little by little, day by day.", author: "Heraclitus" },
    { quote: "Continuous learning is the minimum requirement for success in any field.", author: "Brian Tracy" },
    { quote: "Practice random acts of kindness and senseless acts of beauty.", author: "Anne Herbert" },
    { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { quote: "Listen with curiosity. Speak with honesty. Act with integrity.", author: "Roy T. Bennett" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.", author: "Henry James" },
    { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { quote: "Your character is defined by what you do when no one is watching.", author: "Unknown" },
    { quote: "He who asks is a fool for five minutes, but he who does not ask remains a fool forever.", author: "Chinese Proverb" },
    { quote: "Scatter kindness like confetti.", author: "Unknown" },
    { quote: "A little progress each day adds up to big results.", author: "Satya Nani" },
    { quote: "Treat people the way you want to be treated. Talk to people the way you want to be talked to.", author: "Unknown" },
    { quote: "You are capable of more than you know. Choose a goal that seems right for you and strive to be the best, however hard the path.", author: "E.O. Wilson" },
    { quote: "Kindness costs nothing, but means everything.", author: "Unknown" },
    { quote: "The mind that opens to a new idea never returns to its original size.", author: "Albert Einstein" },
    { quote: "Compassion is a muscle that gets stronger with use.", author: "Gautama Buddha" },
    { quote: "Do not wait until the conditions are perfect to begin. Beginning makes the conditions perfect.", author: "Alan Cohen" },
    { quote: "Character is the real foundation of all worthwhile success.", author: "John Hays Hammond" },
    { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { quote: "One kind word can change someone's entire day.", author: "Unknown" },
    { quote: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
    { quote: "True beauty comes from a gentle and kind character.", author: "Unknown" },
    { quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { quote: "The true measure of a man is how he treats someone who can do him absolutely no good.", author: "Samuel Johnson" },
    { quote: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
    { quote: "Always give without remembering and always receive without forgetting.", author: "Brian Tracy" },
    { quote: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
    { quote: "You cannot do a kindness too soon, for you never know how soon it will be too late.", author: "Ralph Waldo Emerson" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "Respect for ourselves guides our morals, respect for others guides our manners.", author: "Laurence Sterne" },
    { quote: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
    { quote: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt" },
    { quote: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
    { quote: "Character is higher than intellect.", author: "Ralph Waldo Emerson" },
    { quote: "Never stop learning, because life never stops teaching.", author: "Unknown" },
    { quote: "Remember there's no such thing as a small act of kindness. Every act creates a ripple with no logical end.", author: "Scott Adams" },
    { quote: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
    { quote: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela" }
];

/**
 * Returns the quote designated for today based on calendar date.
 * Ensures all users on the same day see the exact same quote,
 * rotating smoothly day by day through all 120+ quotes.
 */
export function getDailyQuote(date = new Date()) {
    const startOfYear = new Date(date.getFullYear(), 0, 1);
    const dayOfYear = Math.floor((date - startOfYear) / (1000 * 60 * 60 * 24));
    // Index offset by year so every year brings a shifted sequence
    const yearOffset = date.getFullYear() * 37;
    const index = Math.abs((dayOfYear + yearOffset) % DAILY_QUOTES.length);
    return DAILY_QUOTES[index];
}
